CREATE TABLE IF NOT EXISTS message_user_message (
    id varchar(64) NOT NULL PRIMARY KEY,
    message_type varchar(32) NOT NULL COMMENT '消息类型：SYSTEM_NOTICE/NORMAL_MESSAGE',
    sender_user_id varchar(64) DEFAULT NULL COMMENT '发送人用户ID',
    sender_name varchar(255) DEFAULT NULL COMMENT '发送人名称',
    receiver_user_id varchar(64) NOT NULL COMMENT '接收人用户ID',
    owner_user_id varchar(64) DEFAULT NULL COMMENT '负责人用户ID',
    title varchar(255) NOT NULL COMMENT '消息标题',
    content text NOT NULL COMMENT '消息内容',
    send_state varchar(32) NOT NULL DEFAULT 'SENT' COMMENT '发送状态：SENT/FAILED',
    read_state varchar(32) NOT NULL DEFAULT 'UNREAD' COMMENT '读取状态：UNREAD/READ',
    send_date_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
    read_date_time datetime DEFAULT NULL COMMENT '读取时间',
    code varchar(255) DEFAULT NULL COMMENT '编码',
    description varchar(255) DEFAULT NULL COMMENT '说明',
    create_date_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_name varchar(255) DEFAULT NULL COMMENT '创建人',
    modify_date_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    modify_name varchar(255) DEFAULT NULL COMMENT '修改人',
    is_delete bit(1) DEFAULT b'0' COMMENT '删除状态',
    label varchar(255) DEFAULT NULL COMMENT '标签',
    sorting int DEFAULT '0' COMMENT '排序',
    version int DEFAULT '1' COMMENT '版本号',
    tenant_id varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '租户id',
    KEY idx_message_user_message_tenant_receiver (tenant_id, receiver_user_id),
    KEY idx_message_user_message_tenant_sender (tenant_id, sender_user_id),
    KEY idx_message_user_message_type (message_type),
    KEY idx_message_user_message_read_state (read_state),
    KEY idx_message_user_message_send_time (send_date_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户消息表';
